name: Build

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x, 26.x]  # specify the Node.js versions you want to test against
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Fix version
        if: github.base_ref == 'main'
        run: yarn fix-version

      - name: Build Project
        env:
            FORCE_COLOR: 3
        run: yarn deploy
