name: Release
on:
  workflow_dispatch:
  push:
    branches: [main, beta]
permissions:
  contents: write
env:
  YARN_IGNORE_ENGINES: true

jobs:
  publish_release:
    if: endsWith(github.repository, 'web-ui')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Fix version
        if: github.ref_name == 'main'
        run: yarn fix-version

      - name: Run check
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BEFORE: ${{ github.event.before }}
